version: '3.3'
services:
    xampp:
        container_name: xampp-server
        ports:
            - '41061:22'
            - '41062:80'
        volumes:
            - ./source_code:/www/app
            - ./rest-api:/www/api
            - ./mysql/data:/mysql/data
        image: 'tomsik68/xampp:8'